//LOGIN
export const USER_LOGGED_IN = 'USER_LOGGED_IN'
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT'
export const IS_AUTHENTICATING = 'IS_AUTHENTICATING'
export const USER_AUTHENTICATED = 'USER_AUTHENTICATED'
export const ERROR_AUTHENTICATION = 'ERROR_AUTHENTICATION'
export const DISMISS_ERROR_LOGIN = 'DISMISS_ERROR_LOGIN'
export const ALTERANDO_DADOS = 'ALTERANDO_DADOS'
export const RESETING_PASSWORD = 'RESETING_PASSWORD'
export const PASSWORD_RESETED = 'PASSWORD_RESETED'
export const CHANGING_PASSWORD = 'CHANGING_PASSWORD'
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED'
export const DADOS_ALTERADOS = 'DADOS_ALTERADOS'
// FÓRUM
export const LOADING_TOPICOS = 'LOADING_TOPICOS'
export const TOPICOS_LOADED = 'TOPICOS_LOADED'
export const SET_TOPICOS = 'SET_TOPICOS'
// TÓPICO
export const SET_NOME_TOPICO = 'SET_NOME_TOPICO'
export const LOADING_POSTS = 'LOADING_POSTS'
export const POSTS_LOADED = 'POSTS_LOADED'
export const SET_POSTS = 'SET_POSTS'
export const ADD_NOVO_POST = 'ADD_NOVO_POST' // (?) Ainda não sei se necessário
// POST
export const SET_KEY_POSTAGEM = 'SET_KEY_POSTAGEM'
export const LOADING_POSTAGEM = 'LOADING_POSTAGEM'
export const POSTAGEM_LOADED = 'POSTAGEM_LOADED'
export const SET_POSTAGEM = 'SET_POSTAGEM'
export const RESPONDE_POSTAGEM = 'RESPONDE_POSTAGEM'